### ISSUE TITLE
ERROR: Eliminate variable from a disjunction Constraint

### ISSUE THREAD

**Issue by ChaahatJain** [NeuralNetworkVerification/Marabou#600] opened 2022-11-10 20:14 UTC
The following code results in the error mentioned in the issue. From simply looking at it, this should be satisfiable. I imagine Marabou is unable to handle unit equations at the moment. 
`
    from maraboupy import MarabouCore
    from maraboupy.Marabou import createOptions

    inputQuery = MarabouCore.InputQuery()
    inputQuery.setNumberOfVariables(1)

    eq1 = MarabouCore.Equation(MarabouCore.Equation.EQ)
    eq1.addAddend(1, 0)
    eq1.setScalar(0)

    # eq2: 1 * var = 1
    eq2 = MarabouCore.Equation(MarabouCore.Equation.EQ)
    eq2.addAddend(1, 0)
    eq2.setScalar(1)

    disjunction = [[eq1], [eq2]]
    MarabouCore.addDisjunctionConstraint(inputQuery, disjunction)

    inputQuery.addEquation(eq2)

    inputQuery.setLowerBound(0, 0)
    inputQuery.setUpperBound(0, 1)

    options = createOptions()
    vars = MarabouCore.solve(inputQuery, options, "")
    print(vars[0])
    print(vars[1:])
`

**Comment by anwu1219** [comment] 2022-11-10 21:06
Hi @ChaahatJain , thanks for pointing this out. This is not the intended behavior and should be fixed by this PR:

https://github.com/NeuralNetworkVerification/Marabou/pull/601

**Closed** 2022-11-11 16:51 UTC
