### ISSUE TITLE
Universal quantifier support in properties

### ISSUE THREAD

**Issue by ZuhraAndleeb** [NeuralNetworkVerification/Marabou#839] opened 2024-09-25 10:32 UTC
How can operators like conjunction, disjunction and negation be added over input/output neurons' constraints in property file? 
Also how can universal quantifiers like 'for all' and 'there exists' be used for input/output neurons' constraints in property file?
Can anyone give an example of a property file in .txt form that contains these operators/quantifiers?

**Comment by MatthewDaggitt** [comment] 2024-09-28 06:01
By design, the Marabou query format does not support any of those operations. You have two options. You can either normalise the properties yourself, or you can use a tool such as [Vehicle](https://github.com/vehicle-lang/vehicle), to write [expressive specifications](https://github.com/vehicle-lang/vehicle/blob/dev/examples/acasXu/acasXu.vcl) that you can compile down to Marabou query files.

**Comment by MatthewDaggitt** [comment] 2024-09-28 06:01
Closing, as not planned to be added to Marabou.

**Closed by MatthewDaggitt** 2024-09-28 06:01 UTC
